# v1.3.21 June 23, 2014
# https://github.com/bevry/base
language: node_js
# ensure npm is the latest (handled via npm install -g npm)
# ensure coffee-script is installed (needed for cake commands)
# ensure dev dependencies are installed (handled via npm install)
# ensure test dependencies are installed (handled via cake install)
install:
  - npm install
  - npm install -g grunt-cli
script: "npm test"
node_js:
  - "0.10"
cache:
  directories:
    - node_modules
notifications:
  email: false
