# Travis CI
# https://travis-ci.org/RobLoach/jquery-once
language: node_js
sudo: false

node_js:
  - "7"
  - "8"
  - "9"
  - "10"

cache:
  directories:
    - node_modules

notifications:
  email: false

after_success: npm run coveralls
