# Docker Compose - jQuery Once Tester
# https://docs.docker.com/compose/
#
# Runs the jQuery Once test suite through Docker Compose.
#
# 1. Install Docker Compose
#
#      https://docs.docker.com/compose/
#
# 2. Run the following to test jQuery Once:
#
#      docker-compose up
#
node:
  # Build off of the Node:7 container:
  #   https://hub.docker.com/r/_/node/
  image: node:7-slim
  # Run the tests through npm
  command: npm test
  # Mount the current working to /app
  volumes:
  - .:/app
  # Start the application in the /app folder
  working_dir: /app
